### ISSUE TITLE
LevelSymbol doesn't seem to work

### ISSUE THREAD

**Issue by SlimMarten** [toomuchdesign/postcss-nested-ancestors#1]
Hi, 
somehow the plugin doesn't work as expected. Here is how I select:

> .myContainer{
> 	
> 	&:hover{
> 
> 		^&__image{
> 			display: none;
> 		}
> 	}
> }

And this is the result:

> ^.myContainer:hover__image{
> 	
> }
> 

It looks like it is ignoring the leveSymbol. Any idea what's wrong?

**Comment by toomuchdesign** [comment]
Hi @SlimMarten, may you post the stack of PostCSS plugins you're using to compile? What result do you expect from the compilation?

**Comment by SlimMarten** [comment]
hi @toomuchdesign ,

this is my stack:

`var processorArray = {
		all: [
			$.postcssPartialImport( {
				extension: 'scss',
				prefix: '_'
			} ),
			$.level4,
			$.postcssSassyMixins,
			$.postcssConditionals,
			$.postcssFor,
			$.postcssSimpleVars,
			$.postcssAssets( {
				loadPaths: [ 'images/' ],
				basePath: assetsPath,
				baseUrl: '../',
				cachebuster: true
			} ),
			$.postcssPropertyLookup,
			$.postcssQuantityQueries,
			$.postcssCenter,
			$.postcssHexrgba,
			$.postcssPosition,
			$.postcssSize,
			$.postcssPxtorem({
				rootValue: 16
				// propWhiteList: ['letter-spacing']
			}),
			$.postcssCalc({
				warnWhenCannotResolve: false,
				mediaQueries: true
			}),
			$.postcssInlineComment,
			$.postcssIfMedia,
			$.postcssInlineSvg( {
				path: `${assetsPath}/images/svg`,
				encode: true
			} ),
			$.autoprefixer( {
				browsers: browserSupport
			} ),
			$.postcssNestedAncestors,
		],

		debug : [
		],

		production : [
		]
};`

Do I need postcss-nested plugin to make postcss-nested-ancestors work?

I actually expect the outcome to be:

`.myContainer{
	
}

.myContainer:hover{
	
}

.myContainer:hover .myContainer__image{
	
}`

**Comment by toomuchdesign** [comment]
`postcssNestedAncestors` doesn't unwrap nested CSS, so your project will need a CSS rules unwrapper like `postcss-nested`, too.

Remember to run `postcssNestedAncestors` **before** the rules unwrapper!

**Comment by SlimMarten** [comment]
I know updated my plugins list but still get the same outcome

- ...

- postcssNestedAncestors

- postcssNested

**Comment by toomuchdesign** [comment]
I see that `level4` plugin already handles CSS unwrapping. So you'll have to remove `postcssNested` from your stack and move `postcssNestedAncestors` just before `level4 `.

**Comment by SlimMarten** [comment]
Yes! Now its working as expected, thanky! But I ran into another problem right now. I have all my styles wrapped in a master class, since the current project I am working on is only a specific module on an existing page.

so what I do is

> 
> .masterclass{
> 	
> 	.myContainer{
> 
> 		&:hover{
> 			
> 			&__image{
> 
> 			}
> 		}
> 	}
> }

And what I get is:

> .masterclass .myContainer:hover .masterclass .myContainer__image{
> 	
> }

What I need is:

> .masterclass .myContainer:hover .myContainer__image{
> 	
> }

Do you have any idea how to prevent that behaviour?

**Comment by toomuchdesign** [comment]
Unfortunately no. `postcssNestedAncestors` builds ancestor's hierarchy starting from the first wrapping element. It might be possible to introduce another top-levelSymbol, but I currently don't see a good use case for it.

**Comment by SlimMarten** [comment]
Too bad. I really like the plugin and what it does but well, in this case I probably can't make use of it.

**Comment by toomuchdesign** [comment]
Since you're using a BEM-like approach, you might remove the wrapping class and use a modificator   instead. But this is another topic. Cheers!
