### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by calmyournerves** [toomuchdesign/postcss-nested-ancestors#40]
Hey there 👋 

Thanks for this plugin! Would it be possible to get a new release with the updated dependencies?

**Comment by toomuchdesign** [comment]
Hi @calmyournerves, thank for writing.
If you mean updating `postcss` dependency, this involves porting `postcss-nested-ancestor` and [`postcss-resolve-nested-selector`](https://github.com/davidtheclark/postcss-resolve-nested-selector) dependency to postcss 8.

Technically feasible, but it would take an effort I'm not able to estimate right now. How would you proceed in this regard?

**Comment by calmyournerves** [comment]
Hey @toomuchdesign, thanks for the quick response!
Sorry, I wasn't precise: I mean releasing a new version of the current master to NPM. The currently published version 2.0.0 depends on `postcss@^6.0.0` which is causing [Dependabot alerts on GitHub](https://github.com/advisories/GHSA-566m-qj78-rww5). The current master depends on `postcss@^8.0.0` which would solve this.

**Comment by toomuchdesign** [comment]
Hi @calmyournerves, turned out `postcss-resolve-nested-selector` is still able to work with postcss 8. I migrated `postcss-nested-ancestors` to postcss 8 and release v3. Tests are green, but I haven't tried it on a real application.

**Comment by calmyournerves** [comment]
Hi @toomuchdesign, thanks so much and sorry for not getting back to you earlier. I just tested it and compared the final CSS output of one of our apps and it seems to work perfectly!
